apiVersion: apps/v1
kind: Deployment
metadata:
  name: reciever
  namespace: functions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reciever
  template:
    metadata:
      labels:
        app: reciever
    spec:
      containers:
        - name: reciever
          image: luccadibenedetto/cloudevent-reciever:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: reciever-logs
              mountPath: /logs
      volumes:
        - name: reciever-logs
          hostPath:
            path: /var/log/reciever
            type: DirectoryOrCreate
