apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-logger
  namespace: functions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-logger
  template:
    metadata:
      labels:
        app: event-logger
    spec:
      containers:
      - name: event-logger
        image: luccadibenedetto/eventlogger:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: events-db
          mountPath: /data
      volumes:
      - name: events-db
        persistentVolumeClaim:
          claimName: events-db
---
apiVersion: v1
kind: Service
metadata:
  name: event-logger
  namespace: functions
spec:
  selector:
    app: event-logger
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: events-db
  namespace: functions
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log/events-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: events-db
  namespace: functions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi