apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reciever
  namespace: functions
spec:
  template:
    spec:
      containers:
        - image: luccadibenedetto/cloudevent-reciever:latest
          env:
            - name: LOG_TO
              value: stdout
