apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: event-source
  namespace: workload-generator
spec:
  template:
    metadata:
      labels:
        app: workload-generator
    spec:
      containers:
      - name: workload-generator
        image: "luccadibenedetto/workload-generator:latest"
        ports:
        - containerPort: 8080
        stdin: true
        tty: true
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        resources:
          requests:
            memory: "7Gi"
            cpu: "3"
          limits:
            memory: "14Gi"
            cpu: "8"
        volumeMounts:
        - name: workload-generator-logs
          mountPath: /logs
      volumes:
      - name: workload-generator-logs
        hostPath:
          path: /var/log/workload-generator
          type: DirectoryOrCreate
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "workload-generator"
          effect: "NoSchedule" 
      nodeSelector:
        dedicated: "workload-generator"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: rabbitmq-broker
      namespace: knative-eventing