apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workload-generator-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: standard
