FROM golang:1.23 AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o workload-generator ./cmd/workload-generator

FROM alpine:3.18
RUN apk add --no-cache bash
WORKDIR /app
COPY --from=builder /app/workload-generator .
COPY ./experiments/* .

ENTRYPOINT ["/bin/bash"]