FROM golang:1.23 AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o reciever ./cmd/reciever

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/reciever .

ENTRYPOINT ["/reciever"]