---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-data
  namespace: metrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: metrics
  labels:
    app: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:stable-scratch
          args:
            - "--storageDataPath=/storage"
            - "--httpListenAddr=:8428"
            - "--retentionPeriod=1w"
          ports:
            - containerPort: 8428
              name: http
          volumeMounts:
            - name: storage
              mountPath: /storage
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: victoriametrics-data
---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: metrics
spec:
  ports:
    - port: 8428
      targetPort: 8428
      name: http
  selector:
    app: victoriametrics