apiVersion: v1
kind: PersistentVolume
metadata:
  name: workload-generator-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: workload-generator-logs
    fsType: ext4
