apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: rabbitmq-trigger
  namespace: knative-eventing
spec:
  broker: rabbitmq-broker

  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: reciever-0
      namespace: functions
    #uri: http://reciever.functions.svc.cluster.local:8080