apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: prometheus-disk  # This will be created by GCE
    fsType: ext4